[information]
name = "fluoromachine"
background = "dark"
author = 'Milianor'

[palette]
fg = '#8BA7A7'
bg = '#262335'
alt_bg = '#241b2f'
currentline = '#463465'
selection = '#463465'
comment = '#495495'
cyan = '#61E2FF'
green = '#72f1b8'
orange = '#ff8b39'
pink = '#FC199A'
purple = '#AF6DF9'
red = '#fe4450'
yellow = '#FFCC00'
cursor_fg = '#282a36'
cursor_bg = '#8BA7A7'
sign_add = '#72f1b8'
sign_change = '#ff8b39'
sign_delete = '#fe4450'
error = '#fe4450'
warning = '#ff8b39'
info = '#61E2FF'
hint = '#61E2FF'
other = '#AF6DF9'
blankline = '#57367C'
active_blankline = '#7E0C4D'
inlay_hint = '#8C57C7'

[Whichkey]
WhichKey = 'fg'
WhichKeySeparator = 'pink'
WhichKeyGroup = 'green'
WhichKeyDesc = 'cyan'
WhichKeyFloat = 'link:NormalFloat'

[LSP]
LspDiagnosticsDefaultError = 'error'
LspDiagnosticsDefaultWarning = 'warning'
LspDiagnosticsDefaultInformation = 'info'
LspDiagnosticsDefaultInfo = 'info'
LspDiagnosticsDefaultHint = 'hint'
LspDiagnosticsVirtualTextError = 'error'
LspDiagnosticsVirtualTextWarning = 'warning'
LspDiagnosticsVirtualTextInformation = 'info'
LspDiagnosticsVirtualTextInfo = 'info'
LspDiagnosticsVirtualTextHint = 'hint'
LspDiagnosticsFloatingError = 'error'
LspDiagnosticsFloatingWarning = 'warning'
LspDiagnosticsFloatingInformation = 'info'
LspDiagnosticsFloatingInfo = 'info'
LspDiagnosticsFloatingHint = 'hint'
DiagnosticHint = 'hint'
DiagnosticInfo = 'info'
DiagnosticError = 'error'
DiagnosticOther = 'other'
DiagnosticVirtualTextHint = 'hint'
DiagnosticVirtualTextInfo = 'info'
DiagnosticVirtualTextWarn = 'warning'
DiagnosticVirtualTextError = 'error'
DiagnosticFloatingHint = 'hint'
DiagnosticFloatingInfo = 'info'
DiagnosticFloatingWarn = 'warning'
DiagnosticFloatingError = 'error'
DiagnosticUnderlineHint = 'hint'
DiagnosticUnderlineInfo = 'info'
DiagnosticUnderlineWarn = 'warning'
DiagnosticUnderlineError = 'error'
DiagnosticSignError = 'error'
DiagnosticSignWarning = 'warning'
DiagnosticSignInformation = 'info'
DiagnosticSignInfo = 'info'
DiagnosticSignHint = 'hint'
DiagnosticSignOther = 'other'
LspDiagnosticsSignError = 'error'
LspDiagnosticsSignWarning = 'warning'
LspDiagnosticsSignInformation = 'info'
LspDiagnosticsSignInfo = 'info'
LspDiagnosticsSignHint = 'hint'
LspDiagnosticsError = 'error'
LspDiagnosticsWarning = 'warning'
LspDiagnosticsInformation = 'info'
LspDiagnosticsInfo = 'info'
LspDiagnosticsHint = 'hint'
LspDiagnosticsUnderlineError = '- - u'
LspDiagnosticsUnderlineWarning = '- - u'
LspDiagnosticsUnderlineInformation = '- - u'
LspDiagnosticsUnderlineInfo = '- - u'
LspDiagnosticsUnderlineHint = '- - u'
LspReferenceRead = '- selection'
LspReferenceText = '- selection'
LspReferenceWrite = '- selection'
LspInlayHint = 'inlay_hint'

[LspSaga]
SagaNormal = 'link:NormalFloat'
SagaWinbarModule = 'link:@namespace'
SagaWinbarInterface = 'link:@type'
SagaWinbarConstructor = 'link:@constructor'
SagaWinbarStruct = 'link:@structure'
SagaWinbarObject = 'link:@field'
SagaWinbarUnit = 'link:@number'
SagaWinbarFile = 'fg'
SagaWinbarSnippet = 'fg'
SagaWinbarText = 'link:@string'
SagaWinbarTypeAlias = 'link:@type'
SagaWinbarEvent = 'link:@function'
SagaWinbarParameter = 'link:@parameter'
SagaWinbarKey = 'link:@keyword'
SagaWinbarValue = 'fg'
SagaWinbarMacro = 'link:Macro'
SagaWinbarNumber = 'link:@number'
SagaWinbarConstant = 'link:@constant'
SagaWinbarFunction = 'link:@function'
SagaWinbarEnum = 'link:@type'
SagaWinbarField = 'link:@field'
SagaWinbarProperty = 'link:@property'
SagaWinbarMethod = 'link:@method'
SagaWinbarClass = 'link:@type'
SagaWinbarFolder = 'link:Directory'
SagaWinbarPackage = 'link:Directory'
SagaWinbarStaticMethod = 'link:@method'
SagaWinbarTypeParameter = 'link:@type'
SagaWinbarEnumMember = 'link:@constant'
SagaWinbarOperator = 'link:@operator'
SagaWinbarNull = 'link:@constant'
SagaWinbarNamespace = 'link:@namespace'
SagaWinbarArray = 'link:@keyword'
SagaWinbarBoolean = 'link:@boolean'
SagaWinbarString = 'link:@string'
SagaWinbarVariable = 'link:@variable'
SagaWinbarFilename = 'fg'
SagaWinbarFolderName = 'fg'
SagaWinbarFileIcon = 'link:Directory'
SagaWinbarSep = 'pink'

[Telescope]
TelescopeTitle = 'yellow - r'
TelescopeNormal = 'link:NormalFloat'
TelescopeSelection = 'fg selection'
TelescopeSelectionCaret = 'pink selection'
TelescopeMatching = 'link:IncSearch'
TelescopeBorder = 'link:WinSeparator'

[NvimTree]
NvimTreeRootFolder = 'link:Directory'
NvimTreeFolderIcon = 'link:Directory'
NvimTreeIndentMarker = 'link:Directory'
NvimTreeNormal = 'link:NormalFloat'
NvimTreeWinSeparator = 'alt_bg alt_bg'
NvimTreeVertSplit = 'link:VertSplit'
NvimTreeFolderName = 'fg'
NvimTreeOpenedFolderName = 'link:Directory'
NvimTreeEmptyFolderName = 'yellow - i'
NvimTreeGitIgnored = 'comment - i'
NvimTreeEndOfBuffer = 'alt_bg'
NvimTreeCursorLine = 'link:CursorLine'
NvimTreeGitStaged = 'sign_add'
NvimTreeGitNew = 'sign_add'
NvimTreeGitRenamed = 'sign_add'
NvimTreeGitDeleted = 'sign_delete'
NvimTreeGitMerge = 'sign_change'
NvimTreeGitDirty = 'sign_change'

[NeoTree]
NeoTreeNormal = 'link:NormalFloat'
NeoTreeNormalNC = 'link:NormalFloat'
NeoTreeEndOfBuffer = 'alt_bg'
NeoTreeRootName = 'link:Directory'
NeoTreeFileName = 'fg'
NeoTreeFileNameOpened = 'purple - b'
NeoTreeFloatBorder = 'link:WinSeparator'
NeoTreeFloatTitle = 'link:Title'
NeoTreeGitAdded = 'sign_add'
NeoTreeGitConflict = 'sign_change'
NeoTreeGitDeleted = 'sign_delete'
NeoTreeGitIgnored = 'comment - i'
NeoTreeGitModified = 'sign_change'
NeoTreeGitUnstaged = 'sign_change'
NeoTreeGitUntracked = 'sign_change'
NeoTreeGitStaged = 'sign_add'
NeoTreeIndentMarker = 'comment'

[Dap]
DapUINormal = 'link:NormalFloat'

[StatusLine]
StatusLine = 'fg alt_bg'
StatusLineNC = 'alt_bg alt_bg'
StatusLineSeparator = 'alt_bg'
StatusLineTerm = 'alt_bg'
StatusLineTermNC = 'alt_bg'

[Dashboard]
DashboardHeader = 'red'
DashboardCenter = 'fg'
DashboardFooter = 'comment'
DashboardProjectTitle = 'link:Title'
DashboardProjectTitleIcon = 'link:Title'
DashboardProjectIcon = 'purple'
DashboardMruTitle = 'link:Title'
DashboardMruIcon = 'link:Title'
DashboardFiles = 'fg'
DashboardShotCutIcon = 'cyan'
DashboardDesc = 'cyan'
DashboardKey = 'purple'
DashboardIcon = 'cyan'
DashboardShotCut = 'purple'

[Navic]
NavicIconsFile = 'fg'
NavicIconsModule = 'link:@namespace'
NavicIconsNamespace = 'link:@namespace'
NavicIconsPackage = 'link:Directory'
NavicIconsClass = 'link:@type'
NavicIconsMethod = 'link:@method'
NavicIconsProperty = 'link:@property'
NavicIconsField = 'link:@field'
NavicIconsConstructor = 'link:@constructor'
NavicIconsEnum = 'link:@type'
NavicIconsInterface = 'link:@type'
NavicIconsFunction = 'link:@function'
NavicIconsVariable = 'link:@Variable'
NavicIconsConstant = 'link:@constant'
NavicIconsString = 'link:@string'
NavicIconsNumber = 'link:@number'
NavicIconsBoolean = 'link:@boolean'
NavicIconsArray = 'link:@keyword'
NavicIconsObject = 'link:@keyword'
NavicIconsKey = 'link:@keyword'
NavicIconsNull = 'link:@constant'
NavicIconsEnumMember = 'link:@constant'
NavicIconsStruct = 'link:Structure'
NavicIconsEvent = 'link:@function'
NavicIconsOperator = 'link:@operator'
NavicIconsTypeParameter = 'link:@type'
NavicText = 'link:@text'
NavicSeparator = 'link:@keyword'

[Notify]
NotifyBackground = 'link:NormalFloat'
NotifyERRORBorder = 'error'
NotifyWARNBorder = 'warning'
NotifyINFOBorder = 'info'
NotifyDEBUGBorder = 'comment'
NotifyTRACEBorder = 'other'
NotifyERRORIcon = 'error'
NotifyWARNIcon = 'warning'
NotifyINFOIcon = 'info'
NotifyDEBUGIcon = 'comment'
NotifyTRACEIcon = 'other'
NotifyERRORTitle = 'error'
NotifyWARNTitle = 'warning'
NotifyINFOTitle = 'info'
NotifyDEBUGTitle = 'comment'
NotifyTRACETitle = 'other'
NotifyERRORBody = 'link:NormalFloat'
NotifyWARNBody = 'link:NormalFloat'
NotifyINFOBody = 'link:NormalFloat'
NotifyDEBUGBody = 'link:NormalFloat'
NotifyTRACEBody = 'link:NormalFloat'

[IndentBlankLine]
IndentBlanklineChar = 'blankline'
IndentBlanklineContextChar = 'active_blankline'
IndentBlanklineSpaceChar = 'blankline'
IndentBlanklineContextSpaceChar = 'active_blankline'

[Hop]
HopNextKey = 'pink - b'
HopNextKey1 = 'cyan - b'
HopUnmatched = 'comment'

[SymbolsOutline]
FocusedSymbol = 'cyan'
SymbolsOutlineConnector = 'comment'

[MiniCursor]
MiniCursorword = '- selection'

[MiniCompletion]
MiniCompletionActiveParameter = 'link:@parameter'

[MiniJump]
MiniJump2dSpot = 'pink'
MiniJump2dSpotUnique = 'purple'

[MiniIndent]
MiniIndentscopeSymbol = 'pink'
MiniIndentscopeSymbolOff = '- -'

[MiniMap]
MiniMapNormal = 'comment alt_bg'
MiniMapSymbolCount = 'purple'
MiniMapSymbolLine = 'pink'
MiniMapSymbolView = 'alt_bg'

[MiniStatusLine]
MiniStatuslineModeNormal = 'bg purple'
MiniStatuslineModeInsert = 'bg green'
MiniStatuslineModeVisual = 'bg yellow'
MiniStatuslineModeReplace = 'bg red'
MiniStatuslineModeCommand = 'purple'
MiniStatuslineDevinfo = 'fg comment'
MiniStatuslineFileinfo = 'fg comment'

[MiniTabLine]
MiniTablineCurrent = 'fg comment'
MiniTablineVisible = 'fg comment'
MiniTablineHidden = 'comment bg'
MiniTablineModifiedCurrent = 'link:MiniTabLineCurrent'
MiniTablineModifiedVisible = 'link:MiniTablineVisible'
MiniTablineModifiedHidden =  'link:MiniTablineHidden'
MiniTablineFill = 'link:NormalFloat'
MiniTablineTabpagesection = 'link:NormalFloat'

[MiniStarter]
MiniStarterCurrent = 'link:CursorLine'
MiniStarterHeader = 'red'
MiniStarterFooter = 'comment'
MiniStarterItem = 'fg'
MiniStarterItemBullet = 'cyan'
MiniStarterItemPrefix = 'cyan'
MiniStarterSection = 'link:Title'
MiniStarterQuery = 'red - b'
