---@class fm.utils
---@field set_hl fun(name: string, val?: vim.api.keyset.highlight, opts?: table): nil
---@field get_hl fun(name: string): vim.api.keyset.get_highlight
---@field on_config fun(opts: table, config: function | table)
